# Dockerfile

FROM ojasgosar/docker-hub:oracle-java8

MAINTAINER Author Name ojas.gosar@gmail.com

COPY target/remote_test-0.0.1.jar /opt/remote_test-0.0.1.jar

WORKDIR /opt/

# RUN java -cp remote_test-0.0.1.jar com.andrewdemaria.test.rmi.remote_test.RMIServer

# CMD java -cp remote_test-0.0.1.jar com.andrewdemaria.test.rmi.remote_test.RMIClient